import type { BenefitDefinition, BenefitInstance, Profile } from '../types';

export function profileFixture(overrides: Partial<Profile> = {}): Profile {
  return {
    user_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    email: 'owner@example.com',
    notification_email: 'owner@example.com',
    timezone: 'America/New_York',
    expiration_reminders_enabled: true,
    reactivation_reminders_enabled: true,
    recent_reset_days: 3,
    language: 'en',
    ...overrides,
  };
}

export function benefitDefinition(overrides: Partial<BenefitDefinition> = {}): BenefitDefinition {
  return {
    id: '22222222-2222-4222-8222-222222222222',
    user_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    account_id: '44444444-4444-4444-8444-444444444444',
    name: '$15 monthly rideshare credit',
    category: 'Transportation',
    description: 'Monthly eligible rideshare credit.',
    notes: '',
    active: true,
    value_kind: 'money',
    amount: 15,
    currency: 'USD',
    unit_label: null,
    minimum_spend: null,
    cashback_percentage: null,
    cashback_cap: null,
    merchant: 'Rideshare Co',
    merchant_category: 'Transportation',
    website: 'https://example.com',
    tags: ['rideshare'],
    eligibility_notes: 'Enrollment required.',
    enrollment_required: true,
    enrollment_deadline: '2028-01-31',
    enrolled_at: '2028-01-15',
    effective_date: '2028-01-01',
    end_date: null,
    display_reset_date: '2028-03-01',
    recurrence_enabled: true,
    recurrence_type: 'monthly',
    recurrence_basis: 'calendar',
    anchor_date: null,
    interval_months: 1,
    expiration_email_enabled: true,
    reactivation_email_enabled: true,
    terms_timezone: 'America/New_York',
    period_value_rules: [],
    origin_source: 'manual',
    origin_template_version_id: null,
    origin_template_stable_key: null,
    origin_template_version: null,
    origin_template_hash: null,
    origin_verified_on: null,
    customized_at: null,
    current_revision_no: 1,
    created_at: '2028-01-01T00:00:00Z',
    updated_at: '2028-01-01T00:00:00Z',
    ...overrides,
  };
}

export function benefitInstance(overrides: Partial<BenefitInstance> = {}): BenefitInstance {
  return {
    instance_id: '11111111-1111-4111-8111-111111111111',
    definition_id: '22222222-2222-4222-8222-222222222222',
    revision_id: '33333333-3333-4333-8333-333333333333',
    account_id: '44444444-4444-4444-8444-444444444444',
    benefit_name: '$15 monthly rideshare credit',
    account_display_name: 'Travel Card — Personal',
    issuer: 'Example Bank',
    category: 'Transportation',
    description: 'Monthly eligible rideshare credit.',
    notes: null,
    merchant: 'Rideshare Co',
    merchant_category: 'Transportation',
    website: 'https://example.com',
    eligibility_notes: 'Enrollment required.',
    tags: ['rideshare'],
    value_kind: 'money',
    available_quantity: 15,
    redeemed_quantity: 5,
    remaining_quantity: 10,
    earned_to_date: 5,
    currency: 'USD',
    unit_label: '$',
    cashback_percentage: null,
    minimum_spend: null,
    period_label: 'February 2028',
    nominal_start: '2028-02-01',
    nominal_end: '2028-02-29',
    period_start: '2028-02-01',
    period_end: '2028-02-29',
    recurrence_type: 'monthly',
    recurrence_basis: 'calendar',
    lifecycle_status: 'active',
    usage_status: 'partial',
    days_remaining: 5,
    expiring_7_days: true,
    expiring_30_days: true,
    recently_activated: false,
    reset_soon: false,
    enrollment_due: false,
    enrollment_missed: false,
    enrollment_due_7_days: false,
    enrollment_due_30_days: false,
    enrollment_required: true,
    enrollment_deadline: '2028-01-31',
    enrolled_at: '2028-01-15',
    definition_active: true,
    recurrence_enabled: true,
    manually_completed_at: null,
    occurrence_key: 'calendar:monthly:2028-02-01',
    instance_version: 1,
    display_reset_date: '2028-03-01',
    supersedes_instance_id: null,
    superseded_by_instance_id: null,
    voided_at: null,
    void_reason: null,
    is_live: true,
    is_audit_version: false,
    search_text: 'rideshare Travel Card Example Bank Transportation',
    origin_source: 'manual',
    origin_template_version_id: null,
    origin_template_stable_key: null,
    origin_template_version: null,
    origin_verified_on: null,
    customized_at: null,
    terms_timezone: 'America/New_York',
    period_value_rules: [],
    ...overrides,
  };
}
